Feature/fortune page
themoment-team/Fortune-front pull request #9
Opened 2022-12-15 08:00 UTC by handsomejeongwoo

## 개요 😫

> 이 pr의 목적을 적어주세요

운세 보기전 페이지와, 결과 페이지를 만들었다. + 반응형까지

2022-12-15 08:14 UTC, Lee-Seungje requested changes

2022-12-15 08:14 UTC, Lee-Seungje commented on src/components/FortunePage/style.js
> +  background-image: url(${fortune});
div 태그에 background로 사진을 넣은 특별한 이유가 있나요?
img 태그를 쓰면 성능 면에서 div에 사진을 넣는 것보다 좋다고 알고 있어서 특별한 이유가 없다면 img 태그를 써도 될 것 같아 보입니다

2022-12-15 08:23 UTC, Lee-Seungje requested changes

2022-12-15 08:23 UTC, Lee-Seungje commented on src/components/ResultFortunePage/index.jsx
> +  };
따로 함수를 만들어서 구성한 이유가 있나요?
특별한 이유가 없다면 함수를 만들지 않고 함수 안의 내용을 바로 필요한 부분에 넣어도 될 것 같습니다

2022-12-15 08:27 UTC, Lee-Seungje requested changes

2022-12-15 08:27 UTC, Lee-Seungje commented on src/components/ResultFortunePage/index.jsx
> +    window.location.href = "/";
location을 쓰면 새로고침이 되어서 history.push를 써도 될 것 같습니다

2022-12-15 08:44 UTC, handsomejeongwoo commented on src/components/ResultFortunePage/index.jsx
> +    window.location.href = "/";
고쳐 보겠습니다

2022-12-15 08:45 UTC, handsomejeongwoo commented on src/components/FortunePage/style.js
> +  background-image: url(${fortune});
포지션 더 적용하기 쉽게 하기위해서 백그라운드 이미지를 사용했습니다.

2022-12-15 12:14 UTC, yebin0310 commented on src/components/MatchPage/style.js
> +  font-family: "MaplestoryOTFBold";
font-family 전체적용으로 바꾼것 같은데 확인해주세요 :)

2022-12-15 12:14 UTC, yebin0310 commented on src/components/ResultFortunePage/index.jsx
> +  };
저도 공감합니다 😏 
함수 안에 내용이 별로없는데 여러개의 함수를 만드는건 불필요한것 같아요

2022-12-15 13:38 UTC, handsomejeongwoo commented on src/components/MatchPage/style.js
> +  font-family: "MaplestoryOTFBold";
삭제 완료 했습니다.

2022-12-15 13:40 UTC, handsomejeongwoo commented on src/components/FortunePage/style.js
> +  background-image: url(${fortune});
이미지 태그안에 자식 태그를 넣을수없어서 이러한 방법을 사용했습니다.

2022-12-15 14:33 UTC, hyeongrok7874 commented on src/components/ResultFortunePage/index.jsx
> +        </S.WrapButton>
```suggestion
        {fortuneBox && 
                <>
                          <ShowFortuneResult />
                          <S.WrapButton>
                                     <S.ReturnButton onClick={returnMainPage}>돌아가기</S.ReturnButton>
                                     <S.ShareButton>공유하기</S.ShareButton>
                          </S.WrapButton>
                </>
        }
```

이런식으로 줄이는게 좋을 것 같네요

2022-12-15 14:39 UTC, handsomejeongwoo commented on src/components/ResultFortunePage/index.jsx
> +        </S.WrapButton>
수정했습니다.

2022-12-15 23:23 UTC, Lee-Seungje approved these changes

2022-12-16 03:10 UTC, yebin0310 approved these changes

2022-12-19 14:04 UTC, merged